import matplotlib.pyplot as plt
from error import exit_w_error

def plot_data(ScatterDataL = None, LineDataL = None, Comment = None):
    """ 
    ARGS:
        ScatterDataL = List of groups' x,y data
                       e.g [ [grp1x, grp1y], [grp2x,grp2y], ...]
        LineDataL    = (Optional) preferably the line data generated by 
                       using beta from linear_regression
    RETURN:
    DESCRIPTION:
        Plots data from ESL by Hastie, Fig. 2.1
    NOTES: 
    DEBUG:
    FUTURE:
    """
    print("{}".format(Comment))
    colors = ['blue', '#ffa500', 'red']
    ### Will plot arbitrary number of data sets up to len(colors) ###
    for grpIdx in range(len(ScatterDataL)):
        plt.scatter(x=ScatterDataL[grpIdx][0], y=ScatterDataL[grpIdx][1],
                    edgecolors=colors[grpIdx], marker="o", facecolors='none',
                    label='group {}'.format(grpIdx))

    ### Plot regressed line fit ###
    if(len(LineDataL) != 0):
        #for lnIdx in range(len(LineDataL)):
        plt.plot(LineDataL[0], LineDataL[1], 'r-')

    plt.legend()
    plt.show()
